# Generated by Django 3.2.9 on 2025-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('callback_url', models.URLField()),
                ('secret_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
