# Generated by Django 3.2.9 on 2025-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='player@iapoker.com', max_length=254),
        ),
    ]
