# Generated by Django 3.2.9 on 2025-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='player@iapoker.com', max_length=254, unique=True),
        ),
    ]
