# Generated by Django 3.2.9 on 2025-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('secret_key', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'authorization',
            },
        ),
    ]
