# Generated by Django 3.2.9 on 2025-05-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_players', models.PositiveIntegerField(default=6)),
                ('initial_chips', models.PositiveIntegerField(default=1000)),
                ('small_blind', models.PositiveIntegerField(default=10)),
                ('big_blind', models.PositiveIntegerField(default=20)),
                ('blind_strategy', models.CharField(choices=[('fixed', 'Fixo'), ('timer', 'Por tempo'), ('hands', 'Por número de mãos')], default='fixed', max_length=10)),
                ('blind_interval', models.PositiveIntegerField(default=600, help_text='Intervalo para aumentar as blinds (segundos ou número de mãos)')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando jogadores'), ('active', 'Em andamento'), ('closed', 'Finalizada')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'table',
            },
        ),
    ]
