# Generated by Django 3.2.9 on 2025-05-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('chips', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_in_hand', models.BooleanField(default=True)),
                ('is_all_in', models.BooleanField(default=False)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('sb', 'Small Blind'), ('bb', 'Big Blind'), ('utg', 'Under the Gun'), ('utg+1', 'UTG+1'), ('utg+2', 'UTG+2'), ('lj', 'Lowjack'), ('hj', 'Hijack'), ('co', 'Cutoff'), ('btn', 'Button'), ('-', 'Indefinida')], default='-', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
            options={
                'db_table': 'table_player',
                'unique_together': {('table', 'player')},
            },
        ),
    ]
