# Generated by Django 3.2.9 on 2025-05-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tableplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('join', 'Entrada na mesa'), ('leave', 'Saída da mesa'), ('start', 'Início da partida'), ('position', 'Distribuição de posições'), ('fold', 'Desistiu (Fold)'), ('check', 'Passou (Check)'), ('call', 'Pagou (Call)'), ('bet', 'Apostou (Bet)'), ('raise', 'Aumentou (Raise)'), ('allin', 'All-in'), ('win', 'Vitória'), ('showdown', 'Showdown'), ('info', 'Informação'), ('error', 'Erro de execução')], max_length=20)),
                ('round_stage', models.CharField(choices=[('preflop', 'Pré-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown'), ('-', 'Não aplicável')], default='-', max_length=10)),
                ('hands_played', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.table')),
            ],
            options={
                'db_table': 'game_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
