# Generated by Django 3.2.9 on 2025-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='hands_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
