# Generated by Django 3.2.9 on 2025-05-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_table_hands_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTurnToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='9ceb35c7ed534b519b5689727a347676', max_length=64, unique=True)),
                ('hands_played', models.PositiveIntegerField(default=0)),
                ('round_stage', models.CharField(default='preflop', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
            options={
                'db_table': 'player_turn_token',
            },
        ),
    ]
