# Generated by Django 3.2.9 on 2025-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_playerturntoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='current_pot',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='flop1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='flop2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='flop3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='river',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='turn',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tableplayer',
            name='card1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tableplayer',
            name='card2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='playerturntoken',
            name='round_stage',
            field=models.CharField(choices=[('preflop', 'Pré-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown'), ('-', 'Não aplicável')], default='preflop', max_length=10),
        ),
        migrations.AlterField(
            model_name='playerturntoken',
            name='token',
            field=models.CharField(default='a0c2c470f7ce47f881238e21a31cbaed', max_length=64, unique=True),
        ),
    ]
