# Generated by Django 3.2.9 on 2025-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250503_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='current_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='last_raise_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerturntoken',
            name='token',
            field=models.CharField(default='9a4f3a91c39442ce8ca87a054f1520d1', max_length=64, unique=True),
        ),
    ]
