# Generated by Django 3.2.9 on 2025-05-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250503_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerturntoken',
            name='token',
            field=models.CharField(default='f40eb67a51e94836aa2282c9e8a32673', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ActionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('preflop', 'Pré-flop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown'), ('-', 'Não aplicável')], max_length=10)),
                ('needs_to_act', models.BooleanField(default=True)),
                ('amount_invested', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
            options={
                'db_table': 'action_state',
                'unique_together': {('table', 'player', 'stage')},
            },
        ),
    ]
