# Generated by Django 3.2.9 on 2025-05-03 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250503_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerturntoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
