# Generated by Django 3.2.9 on 2025-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_playerturntoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='deck',
            field=models.TextField(blank=True, null=True),
        ),
    ]
